name: 'dbt_jinjat'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=1.2.0", "<2.0.0"]
macro-paths: ["macros"]

target-path: "target" 
clean-targets:        
  - "target"
  - "dbt_packages"
