version: 2

exposures:
  - name: customer_app
    type: application
    owner: &owner
      name: Burak
      email: burak@email.com
    meta:
      jinjat:
        refine:
          menu_icon: AutoAwesome
          actions:
            delete: _delete_customers
          resources:
            create: _create_customers
            list: _list_customers
            show: _get_customer
            edit: _patch_customers
  - name: sales_dashboard_exposure
    type: dashboard
    depends_on: []
    owner:
      name: Burak
      email: burak@email.com
    description: Monthly sales dashboard used by the executive team.
    url: https://looker.company.com/dashboards/123
        

analyses:
  - name: example_endpoint
    description: Example list to demonstrate Jinjat
    config:
      jinjat:
        method: get
        openapi:
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        test:
                          type: integer
          parameters:
            - in: query
              name: number
              schema:
                type: number
                default: 1
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    number:
                      type: number
                      default: 1
