
name: 'dbt_jinjat_tests'
version: '1.0.0'
config-version: 2

profile: 'jaffle_shop'
analysis-paths: ["analyses"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
model-paths: ["models"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"