# fly.toml app configuration file generated for dbt-jinjat-integration-tests on 2023-10-26T15:07:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dbt-jinjat-integration-tests"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"

[env]
  LOG_LEVEL = "debug"

[[services]]
  protocol = "tcp"
  internal_port = 8581
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
