jaffle_shop:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_DATABASE_PATH', './jaffle_shop.duckdb') }}"
      # settings:
      #   access_mode: READ_ONLY
      extensions:
        - httpfs
        - parquet
        - json